micronaut:
  application:
    name: pixKeymanagerRest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keyManager:
      address: ${KEY_MANAGER_HOST}:${KEY_MANAGER_PORT}

##
# Necessary for correct serialization of a LocalDateTime
# created from a protobuf Timestamp
##
jackson:
  serialization:
    writeDatesAsTimestamps: false