micronaut:
  application:
    name: pixKeymanagerRest

datasources:
  default:
    url: ${DB_URL}/${DB_SCHEMA}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.format_sql: true
jpa.default.properties.hibernate.show_sql: true
