micronaut:
  application:
    name: pixKeymanagerRest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keyManager:
      address: ${KEY_MANAGER_HOST}:${KEY_MANAGER_PORT}
